new icon:
  - any: [icons/*.svg]
    status: added
update icon/data:
  - any: [icons/*.svg]
    status: modified
docs:
  - any: ['*.md']
    status: modified
meta:
  - any:
      [
        '.github/*',
        'scripts/*',
        'tests/*',
        '.husky/*',
        '*.mjs',
        '*.d.ts',
        '*.json',
        '*.toml',
        '*',
      ]
    status: modified
