name: Documentation
description: Report problems and suggest ideas for the documentation
labels: [docs]

body:
  - type: markdown
    attributes:
      value: Before opening a new issue, please search for duplicate or closed issues.

  - type: dropdown
    attributes:
      label: Kind of issue
      description: |
        Select "other" if you don't see your issue kind here. If you do, please explain
        why in the description below.
      options: [improvement, mistake, other]

  - type: textarea
    attributes:
      label: Description
      description: |
        Anything relevant, for example:
        - A (perma)link to the documentation
        - For improvements: Suggested for how to improve
        - For mistakes: Suggested fixes
    validations:
      required: true
