name: Documentation
description: Report problems and suggest ideas for the documentation
labels: [docs]

body:
  - type: markdown
    attributes:
      value: Before opening a new issue, please search for duplicate or closed issues.

  - type: dropdown
    attributes:
      label: Kind of issue
      description: >-
        If your issue type is not here, select "other" and explain in the
        "Description" field below.
      options: [improvement, mistake, other]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Include as much detail as possible, for example:
        - A (perma)link to the documentation in question
        - Suggestions for how to change the docs
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Contributing
      description: >-
        This is an open source project and we welcome contributions. Do you want help
        implement this?
      options:
        - "Yes"
        - "No"
