name: Icon request
description: Request a new icon for Simple Icons
title: "Request: "
labels: [new icon]

body:
  - type: markdown
    attributes:
      value: >-
        We won't add non-brand icons or anything related to illegal services. If in
        doubt, open an issue and we'll have a look. Before opening a new issue, make
        sure it isn't covered by an existing issue. Please search for [issues with the
        `new icon`
        label](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+label%3A%22new+icon%22+is%3Aopen)
        (including closed issues) before you continue. If you find one for the brand
        you're requesting then leave a comment on it or add a reaction to the original
        post. Also take a look at our [contributing
        guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)
        for more details.

  - type: input
    attributes:
      label: Brand Name
    validations:
      required: true

  - type: input
    attributes:
      label: Website
      description: >-
        For non-web brands you can add a relevant link or simply put "None" if you don't
        think there's a website.

    validations:
      required: true

  - type: input
    attributes:
      label: Alexa Rank
      description: >-
        Provide either an [Alexa rank](https://www.alexa.com/siteinfo) or the number
        of GitHub stars. If these are not available or insufficient you can still open
        the issue. Please provide any information regarding the brand's popularity you
        think is relevant in the description below.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Official resources for icon and color
      description: >-
        Media kits, brand guidelines, SVG files, etc. We strongly encourage you to do
        some research here as it will help implement your request faster, although you
        can set this to none if you are unable to find any resources.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the brand? For example:
        - Are there multiple options for the logo and/or color?
        - Is the icon licensed?
        - If the brand isn't popular enough by the default criteria, how can we assess the popularity instead?
        - If you think the brand might not be accepted for other reasons, why do you think it should be considered?

  - type: dropdown
    attributes:
      label: Contributing
      description: >-
        This is an open source project and we welcome contributions. Do you want to
        add this icon?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
