name: Icon update
description: Help us improve by reporting outdated icons
title: "Update: "
labels: [icon outdated]

body:
  - type: markdown
    attributes:
      value: >-
        Before opening a new issue, make sure it isn't covered by an existing issue.
        Please search for [issues with the `icon outdated`
        label](https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+label%3A%22icon+outdated%22+is%3Aopen)
        (including closed issues) before you continue. If you find one for the brand
        you're reporting then leave a comment on it or add a reaction to the original
        post. Also take a look at our [contributing
        guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)
        for more details.

  - type: input
    attributes:
      label: Brand Name
      placeholder: "Example: Simple Icons"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Official resources for icon and color
      description: >-
        Media kits, brand guidelines, SVG files, etc. We strongly encourage you to do
        some research here as it will help implement your request faster, although you
        can put "None" if you are unable to find any resources.
      placeholder: |
        Example:
        svg source: https://github.com/simple-icons/simple-icons/blob/develop/icons/simpleicons.svg
        color: #111111 from website header

    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Comments
      description: |
        Is there anything else we should know about the brand? For example:
        - Are there multiple options for the logo and/or color?
        - Is the icon licensed?
        - If the brand isn't popular enough by the default criteria, how can we assess the popularity instead?
        - If you think the brand might not be accepted for other reasons, why do you think it should be considered?
      placeholder: "Example: There are two variants of this icon..."

  - type: dropdown
    attributes:
      label: Contributing
      description: >-
        This is an open source project and we welcome contributions. Do you want to
        update this icon?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
