name: Icon request
description: Request a new icon for Simple Icons
title: "Request: "
labels: [new icon]

body:
  - type: markdown
    attributes:
      value: >-
        We won't add non-brand icons or anything related to illegal services. If in
        doubt, open an issue and we'll have a look. Before opening a new issue, please
        search for duplicate or closed issues or PRs. If you find one for the brand
        you're requesting then leave a comment on it or add a reaction to the original
        post. Also take a look at our 
        [contributing guidelines](https://github.com/simple-icons/simple-icons/blob/develop/CONTRIBUTING.md)
        for more details.

  - type: input
    attributes:
      label: Brand Name
    validations:
      required: true

  - type: input
    attributes:
      label: Website
    validations:
      required: true

  - type: input
    attributes:
      label: Alexa Rank
      description: >-
        The Alexa rank can be retrieved at https://www.alexa.com/siteinfo/.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Official resources for icon and color
      description: >-
        Media kits, brand guidelines, SVG files, etc. We strongly encourage you to do
        some research here as it will help implement your request faster, although you
        can set this to none if you are unable to find any resources.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional Comments
      description: Is there anything else that should be considered for this icon?
