name: Packages
description: Report problems and suggest ideas for the packages
labels: [package]

body:
  - type: markdown
    attributes:
      value: >-
        Before opening a new issue, make sure it isn't covered by an existing issue.
        Please search for [issues with the `package` label][package-issues] (including
        closed issues) before you continue.


        [package-issues]: https://github.com/simple-icons/simple-icons/issues?q=is%3Aissue+label%3Apackage+is%3Aopen

  - type: dropdown
    attributes:
      label: Kind of issue
      description: >-
        If your issue type is not here, select "other" and explain in the
        "Description" field below.
      options: [Improvement, Bug, Other]
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Which packages do this issue concern?
      options: [NPM, Packagist]
      multiple: true
    validations:
      required: true

  - type: input
    attributes:
      label: Package Version
      placeholder: "Example: 5.11.0"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other Software
      description: >-
        The software that you are using the package with (Node.js & NPM, PHP & Packagist,
        Browser(s), other) and their versions. You can put "None" if you are unsure.
      placeholder: |
        Example:
        Node.js v16
        Chrome 92.0.4515.159 (Official Build) (64-bit)
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Anything relevant, for example:
        - For bugs: "Steps to reproduce" and "Expected behavior"
        - For improvements: An example of a use case
      placeholder: "Example: The NPM package does not work for my use case..."
    validations:
      required: true
