name: Packages
description: Report problems and suggest ideas for the packages
labels: [package]

body:
  - type: markdown
    attributes:
      value: Before opening a new issue, please search for duplicate or closed issues.

  - type: dropdown
    attributes:
      label: Kind of issue
      description: >-
        Select "other" if you don't see your issue kind here. If you do, please
        explain why in the "Description" field below.
      options: [improvement, bug, other]

  - type: dropdown
    attributes:
      label: Which package does this issue concern?
      options: [NPM, Packagist]
      multiple: true
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: |
        Anything relevant, for example:
        - For bugs: "Steps to reproduce" and "Expected behavior"
        - For improvements: An example of a use case
        - Package issues: Version information
          - For JavaScript/NodeJS: $ node --version
          - For PHP/Packagist: $ composer --version
        - etc.
    validations:
      required: true
