# Get the current version
name: Get version

on:
  workflow_call:
    outputs:
      version:
        description: The version of the project
        value: ${{ jobs.get-version.outputs.version }}

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - name: Get version from package.json
        id: get-version
        run: |
          version="$(grep version -m 1 -i package.json | sed 's/[ \",:version]//g')"
          echo "version=$version" >> $GITHUB_OUTPUT
