name: Get issue/pull request labels
description: Get the current labels of an issue or pull request through the GitHub API

inputs:
  issue_number:
    description: Issue or pull request number to get labels from
    required: true
outputs:
  labels:
    description: Labels of the issue or pull request
    value: ${{ steps.get-labels.outputs.labels }}

runs:
  using: composite
  steps:
    - id: get-labels
      shell: sh
      run: |
        labels="$(gh api 'repos/simple-icons/simple-icons/issues/${{ inputs.issue_number }}' --jq '.labels.[].name')"
        echo "labels=$labels" >> $GITHUB_OUTPUT
